# Generated by Django 3.2.2 on 2021-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_books_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
